spring:
  main:
    banner-mode: 'off'
  datasource:
      schema: classpath:import.sql
#      url: jdbc:mysql://127.0.0.1/test
      url: jdbc:mysql://127.0.0.1/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8&allowMultiQueries=true&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      tomcat:
        default-auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
mybatis:
  mapper-locations: classpath*:**/mapper/*.xml