spring:
  main:
    banner-mode: 'off'
  datasource:
#      url: jdbc:mysql://127.0.0.1/test
      url: jdbc:mysql://127.0.0.1/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8&allowMultiQueries=true
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      tomcat:
        default-auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update